'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { Analytics } from "@vercel/analytics/react"
import { useStoreData } from '@/hooks/data'
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const dataDummy = useStoreData()

  return (
    <html lang="en" className="h-full scroll-smooth">
      <body className={`${inter.className} min-h-screen`}>
        <main className={`flex flex-col justify-between min-h-screen ${dataDummy?.backgroundColorHEX ? `bg-[#${dataDummy?.backgroundColorHEX}]` : 'bg-white'}`}>
          <Header />
          <div className="p-4 xl:max-w-screen-xl m-auto w-full">
            {children}
            <Analytics />
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
