import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full scroll-smooth">
      <body className={`${inter.className} min-h-screen`}>
        <main className="flex flex-col justify-between min-h-screen">
          <Header />
          <div className="p-4 xl:max-w-screen-xl">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
